### ISSUE TITLE
page text vanishes

### ISSUE THREAD

**Issue by jeremyandrews** [mmolinari/oggiposso#1]
If you select "Scegli un giorno" from the date drop down, the page disappears.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/402892/103150254-9f562980-4772-11eb-8184-eeb01744a4da.png">

**Comment by mmolinari** [comment]
Fixed here https://github.com/mmolinari/oggiposso/commit/8cd43b08b415869b79c15fc346a5c2f17e6a9647
Thanks!
