### ISSUE TITLE
map is overlaying on footnotes

### ISSUE THREAD

**Issue by jeremyandrews** [mmolinari/oggiposso#2]
On a small laptop (Macbook Air) the map is overlayed on top of the footnotes:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/402892/103621921-3fac0b00-4f36-11eb-9bb0-91b3cd1e2d6b.png">

**Comment by mmolinari** [comment]
Fixed here https://github.com/mmolinari/oggiposso/commit/ca887194e0a354b909cd244d9a9d2075540ad389, thanks
